print(['Traceback (most recent call last):\n', '  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen\n    chunked=chunked)\n', '  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request\n    six.raise_from(e, None)\n', '  File "<string>", line 3, in raise_from\n', '  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 383, in _make_request\n    httplib_response = conn.getresponse()\n', '  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse\n    response.begin()\n', '  File "/usr/lib/python3.6/http/client.py", line 297, in begin\n    version, status, reason = self._read_status()\n', '  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status\n    raise RemoteDisconnected("Remote end closed connection without"\n', 'http.client.RemoteDisconnected: Remote end closed connection without response\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send\n    timeout=timeout\n', '  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen\n    _stacktrace=sys.exc_info()[2])\n', '  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 367, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n', '  File "/home/huyanhtemp/.local/lib/python3.6/site-packages/six.py", line 692, in reraise\n    raise value.with_traceback(tb)\n', '  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen\n    chunked=chunked)\n', '  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request\n    six.raise_from(e, None)\n', '  File "<string>", line 3, in raise_from\n', '  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 383, in _make_request\n    httplib_response = conn.getresponse()\n', '  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse\n    response.begin()\n', '  File "/usr/lib/python3.6/http/client.py", line 297, in begin\n    version, status, reason = self._read_status()\n', '  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status\n    raise RemoteDisconnected("Remote end closed connection without"\n', "urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))\n", '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/home/huyanhtemp/websim/common/simulator.py", line 118, in multi_simulate\n    sim_job_response = sess.get(sim_job_url, data="", headers = headers)\n', '  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in get\n    return self.request(\'GET\', url, **kwargs)\n', '  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request\n    resp = self.send(prep, **send_kwargs)\n', '  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send\n    r = adapter.send(request, **kwargs)\n', '  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 490, in send\n    raise ConnectionError(err, request=request)\n', "requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))\n"])